apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payment-service
  name: payment-service
  namespace: micro-mart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  strategy: {}
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - image: 172.25.46.10:32000/payment-service
          name: payment-service
          envFrom:
            - configMapRef:
                name: payment-service-config
            - secretRef:
                name: payment-database-secrets
            - secretRef:
                name: internal-service-token-secrets
          # 하나씩 가져오는 예제
          # env:
          #   - name: DATABASE_URL
          #     valueFrom:
          #       secretKeyRef:
          #         name: database-secrets
          #         key: DATABASE_URL
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
          resources: {}

status: {}
