apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: micro-mart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  strategy: {}
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - image: 172.25.46.10:32000/api-gateway
          name: api-gateway
          envFrom:
            - configMapRef:
                name: api-gateway-config
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              # memory만 최소한으로 제한 걸어놓고 k6으로 부하테스트 이후 정확한 제한 값 산출
              memory: "256Mi"
status: {}
