apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-service
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  strategy: {}
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - image: notification-service
          imagePullPolicy: IfNotPresent
          name: notification-service
          ports:
            - containerPort: 8000
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          envFrom:
            - configMapRef:
                name: notification-service-config
            - secretRef:
                name: nats-secrets
          # 하나씩 가져오는 예제
          # env:
          #   - name: DATABASE_URL
          #     valueFrom:
          #       secretKeyRef:
          #         name: database-secrets
          #         key: DATABASE_URL
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              # memory만 최소한으로 제한 걸어놓고 k6으로 부하테스트 이후 정확한 제한 값 산출
              memory: "256Mi"
      volumes:
        - name: tmp
          emptyDir: {}

status: {}
