apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-service
  name: notification-service
  namespace: micro-mart
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: notification-service
status:
  loadBalancer: {}
