apiVersion: v1
data:
  DEBUG: "true"
  LOG_FORMAT: json
  NATS_CONNECT_TIMEOUT_SECONDS: "5"
  NATS_SUBJECT_ORDER_COMPLETED: order.completed
  NOTIFICATION_FAILURE_RATE: "0.0"
  NOTIFICATION_SEND_DELAY_MS: "0"
  OTEL_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  OTEL_EXPORTER_OTLP_INSECURE: "true"
  OTEL_PYTHON_EXCLUDED_URLS: health
  SERVICE_NAME: notification-service
  SERVICE_VERSION: 0.1.0
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: micro-mart
