apiVersion: v1
data:
  CHAOS_DB_SLOWQUERY: "false"
  CHAOS_FAILURE_RATE: "0.3"
  CHAOS_LATENCY_MS: "0"
  DEBUG: "true"
  LOG_FORMAT: json
  OTEL_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  OTEL_EXPORTER_OTLP_INSECURE: "true"
  OTEL_PYTHON_EXCLUDED_URLS: health
  SERVICE_NAME: payment-service
  SERVICE_VERSION: 0.1.0
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: micro-mart
