apiVersion: v1
data:
  ACCESS_TOKEN_EXPIRE_MINUTES: "15"
  DEBUG: "true"
  JWT_ALGORITHM: RS256
  JWT_PRIVATE_KEY: ""
  JWT_PRIVATE_KEY_FILE: /etc/secrets/private.pem
  JWT_PUBLIC_KEY: ""
  JWT_PUBLIC_KEY_FILE: /etc/secrets/public.pem
  LOG_FORMAT: json
  OTEL_ENABLED: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  OTEL_EXPORTER_OTLP_INSECURE: "true"
  OTEL_PYTHON_EXCLUDED_URLS: health
  REFRESH_TOKEN_EXPIRE_DAYS: "7"
  SERVICE_NAME: user-service
  SERVICE_VERSION: 0.1.0
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: micro-mart
