apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
  namespace: micro-mart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  strategy: {}
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - image: 172.25.46.10:32000/user-service
          name: user-service
          envFrom:
            - configMapRef:
                name: user-service-config
            - secretRef:
                name: user-database-secrets
            - secretRef:
                name: redis-secrets
          # 하나씩 가져오는 예제
          # env:
          #   - name: DATABASE_URL
          #     valueFrom:
          #       secretKeyRef:
          #         name: database-secrets
          #         key: DATABASE_URL
          volumeMounts:
            - name: jwt-keys
              readOnly: true
              mountPath: /etc/secrets
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
          resources: {}
      volumes:
        - name: jwt-keys
          secret:
            secretName: jwt-keys

status: {}
